title: "Humberto Monteiro"
description: "| enginneer, phd | fem | data | dev | ai |"
#url: http://hasmonteiro.github.io # Site url, without a slash at the end.
signoff: "hasmonteiro" # Your name

# permalink: /:title/

links:
  - name: /about_me
    url: /about/
  - name: /research
    url: /research/
  - name: /publications
    url: /publications
  - name: /projects
    url: /projects
  - name: /education
    url: /education	
  - name: /posts
    url: /posts	
  - name: /cv
    url: /cv
  - name: /contact
    url: /contact	

defaults:
  - values:
      layout: "default"

include: ['_pages']	  

# facebook_appid: # APP ID for like button, remove from /_includes/share.html if unwanted.
# google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
# share: false # Turn on twitter and facebook share buttons